name: "Alembic Migration Lint with Squawk"
description: "Leverages Squawk to lint Alembic migrations"
branding:
  icon: "check-square"
  color: "blue"

inputs:
  migrations_path:
    description: "Path to the folder containing your 'versions' subfolder."
    required: true
  alembic_config:
    description: "Path to alembic.ini."
    required: false
    default: "alembic.ini"
  runner:
    description: >
      Command prefix for running Python commands.
      Use "poetry" for Poetry, "pipenv" for Pipenv, "pdm" for PDM, "uv" for uv,
      or leave empty (or set to "none") to use the system interpreter.
    required: false
    default: "poetry"

outputs:
  changed:
    description: "Indicates whether any new migrations were found and processed."
    value: ${{ steps.generate-sql.outputs.changed }}

runs:
  using: "composite"
  steps:
    - name: Find changed migrations
      id: modified-migrations
      uses: dorny/paths-filter@v3.0.2
      with:
        list-files: shell
        filters: |
          migrations:
            - '${{ inputs.migrations_path }}/versions/*.py'

    - name: Generate migration SQL
      id: generate-sql
      shell: bash
      run: |
        runner="${{ inputs.runner }}"
        if [ "${{ steps.modified-migrations.outputs.migrations }}" != "true" ]; then
          echo "No new migrations found."
          echo "changed=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        if [ -z "$runner" ] || [ "$runner" = "none" ]; then
          CMD="python"
          ALEMBIC_CMD="alembic"
        elif [ "$runner" = "uv" ]; then
          CMD="uv run python"
          ALEMBIC_CMD="uv run alembic"
        elif [ "$runner" = "poetry" ] || [ "$runner" = "pipenv" ] || [ "$runner" = "pdm" ]; then
          CMD="$runner run python"
          ALEMBIC_CMD="$runner run alembic"
        else
          CMD="$runner python"
          ALEMBIC_CMD="$runner alembic"
        fi

        echo "Using command prefix: $CMD"
        echo "Detected changed migrations: ${{ steps.modified-migrations.outputs.migrations_files }}"

        ALEMBIC_RANGE=$($CMD ${{ github.action_path }}/scripts/range_from_files.py \
          --config "${{ inputs.alembic_config }}" \
          --files ${{ steps.modified-migrations.outputs.migrations_files }})
        echo "Alembic range: $ALEMBIC_RANGE"

        $ALEMBIC_CMD -c "${{ inputs.alembic_config }}" upgrade "$ALEMBIC_RANGE" --sql > migrations.sql

        # Set output for changed migrations.
        echo "changed=true" >> $GITHUB_OUTPUT

    - name: Squawk Check for New Migrations
      if: ${{ steps.generate-sql.outputs.changed == 'true' }}
      uses: sbdchd/squawk-action@v2
      with:
        pattern: migrations.sql
